export const componentData = [
    { id: 'buttons-6506', type: 'button', label: 'Linear Submit Button', targetSection: 'buttons', icon: '🔘', variant: 'outline', imagePath: '/images/buttons/buttonsl' },
    { id: 'footer-8008', type: 'foote', label: 'Linear Footer', targetSection: 'footer', icon: '🏷️', variant: 'multicolumn', imagePath: '/images/footer/footerl' },
    { id: 'imageTop-4505', type: 'image', label: 'Banner Image', targetSection: 'imageTop', icon: '🖼️', variant: 'banner', imagePath: '/images/image/image1' },
    { id: 'login-2503', type: 'login', label: 'Repating Lines Login', targetSection: 'login', icon: '🔐', variant: 'dark', imagePath: '/images/login/loginrl' },
    { id: 'contactForm-6006', type: 'contact', label: 'Bordered Contact Form', targetSection: 'contactForm', icon: '✉️', variant: 'bordered', imagePath: '/images/contact/contact-bordered' },
    { id: 'buttonsAlt-7007', type: 'button', label: 'LLinear Reset Button', targetSection: 'buttonsAlt', icon: '🔘', variant: 'text', imagePath: '/images/buttons/buttonll' },
    { id: 'content-4004', type: 'content', label: 'Dark Content Section', targetSection: 'content', icon: '📝', variant: 'dark', imagePath: '/images/content/image1' },
    { id: 'navbar-2002', type: 'navbar', label: 'Transparent Navbar', targetSection: 'navbar', icon: '📋', variant: 'transparent', imagePath: '/images/navbars/navbar-transparent' },
    { id: 'imageLeft-5005', type: 'image', label: 'Team Image', targetSection: 'imageLeft', icon: '🖼️', variant: 'team', imagePath: '/images/images/image-team' },
    { id: 'content-4005', type: 'content', label: 'Accent Content Section', targetSection: 'content', icon: '📝', variant: 'accent', imagePath: '/images/content/image2' },
    { id: 'buttons-6507', type: 'button', label: 'Gradient Submit Button', targetSection: 'buttons', icon: '🔘', variant: 'gradient', imagePath: '/images/buttons/buttonsg' },
    { id: 'login-2504', type: 'login', label: 'Gradient Login', targetSection: 'login', icon: '🔐', variant: 'social', imagePath: '/images/login/loging' },
    { id: 'imageTop-4506', type: 'image', label: 'Hero Image', targetSection: 'imageTop', icon: '🖼️', variant: 'hero', imagePath: '/images/image/image-hero' },
    { id: 'navbar-2003', type: 'navbar', label: 'Green Navbar', targetSection: 'navbar', icon: '📋', variant: 'green', imagePath: '/images/navbars/navbar-green' },
    { id: 'imageLeft-5006', type: 'image', label: 'Gallery Image', targetSection: 'imageLeft', icon: '🖼️', variant: 'gallery', imagePath: '/images/image/image2' },
    { id: 'footer-8009', type: 'footer', label: 'Gradient Footer', targetSection: 'footer', icon: '🏷️', variant: 'simple', imagePath: '/images/footer/footerg' },
    { id: 'buttonsAlt-7008', type: 'button', label: 'Gradient Reset Button', targetSection: 'buttonsAlt', icon: '🔘', variant: 'icon', imagePath: '/images/buttons/buttonlg' },
    { id: 'contactForm-6007', type: 'contact', label: 'Colorful Contact Form', targetSection: 'contactForm', icon: '✉️', variant: 'colorful', imagePath: '/images/contact/contact-colorful' },
    { id: 'buttons-6508', type: 'button', label: 'Repeat Lines Submit Button', targetSection: 'buttons', icon: '🔘', variant: 'primary', imagePath: '/images/buttons/buttonsrl' },
    { id: 'imageTop-4507', type: 'image', label: 'Product Image', targetSection: 'imageTop', icon: '🖼️', variant: 'product', imagePath: '/images/image/3' },
    { id: 'footer-8010', type: 'footer', label: 'Repeating Lines Footer', targetSection: 'footer', icon: '🏷️', variant: 'dark', imagePath: '/images/footer/footerrl' },
    { id: 'content-4006', type: 'content', label: 'Light Content Section', targetSection: 'content', icon: '📝', variant: 'light', imagePath: '/images/content/image3' },
    { id: 'contactForm-6008', type: 'contact', label: 'Minimal Contact Form', targetSection: 'contactForm', icon: '✉️', variant: 'minimal', imagePath: '/images/contact/contact-minimal' },
    { id: 'login-2505', type: 'login', label: 'Simple Login', targetSection: 'login', icon: '🔐', variant: 'simple', imagePath: '/images/login/loginl' },
    { id: 'navbar-2004', type: 'navbar', label: 'Dark Navbar', targetSection: 'navbar', icon: '📋', variant: 'dark', imagePath: '/images/navbars/navbar-dark' },
    { id: 'buttonsAlt-7009', type: 'button', label: 'Repeat Lines Reset Button', targetSection: 'buttonsAlt', icon: '🔘', variant: 'secondary', imagePath: '/images/buttons/buttonlrl' },
    { id: 'imageLeft-5007', type: 'image', label: 'Feature Image', targetSection: 'imageLeft', icon: '🖼️', variant: 'feature', imagePath: '/images/image/image-feature' }
];